/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Files": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Files.id"];
          createdOn?: parameters["rowFilter.Files.createdOn"];
          updatedOn?: parameters["rowFilter.Files.updatedOn"];
          deletedOn?: parameters["rowFilter.Files.deletedOn"];
          name?: parameters["rowFilter.Files.name"];
          storageProviderId?: parameters["rowFilter.Files.storageProviderId"];
          storageProviderPath?: parameters["rowFilter.Files.storageProviderPath"];
          type?: parameters["rowFilter.Files.type"];
          size?: parameters["rowFilter.Files.size"];
          description?: parameters["rowFilter.Files.description"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Files"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Files */
          Files?: definitions["Files"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Files.id"];
          createdOn?: parameters["rowFilter.Files.createdOn"];
          updatedOn?: parameters["rowFilter.Files.updatedOn"];
          deletedOn?: parameters["rowFilter.Files.deletedOn"];
          name?: parameters["rowFilter.Files.name"];
          storageProviderId?: parameters["rowFilter.Files.storageProviderId"];
          storageProviderPath?: parameters["rowFilter.Files.storageProviderPath"];
          type?: parameters["rowFilter.Files.type"];
          size?: parameters["rowFilter.Files.size"];
          description?: parameters["rowFilter.Files.description"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Files.id"];
          createdOn?: parameters["rowFilter.Files.createdOn"];
          updatedOn?: parameters["rowFilter.Files.updatedOn"];
          deletedOn?: parameters["rowFilter.Files.deletedOn"];
          name?: parameters["rowFilter.Files.name"];
          storageProviderId?: parameters["rowFilter.Files.storageProviderId"];
          storageProviderPath?: parameters["rowFilter.Files.storageProviderPath"];
          type?: parameters["rowFilter.Files.type"];
          size?: parameters["rowFilter.Files.size"];
          description?: parameters["rowFilter.Files.description"];
        };
        body: {
          /** Files */
          Files?: definitions["Files"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Files: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    createdOn?: string;
    updatedOn?: string;
    deletedOn?: string;
    name?: string;
    storageProviderId: string;
    storageProviderPath: string;
    type?: string;
    size?: number;
    description?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** Files */
  "body.Files": definitions["Files"];
  "rowFilter.Files.id": string;
  "rowFilter.Files.createdOn": string;
  "rowFilter.Files.updatedOn": string;
  "rowFilter.Files.deletedOn": string;
  "rowFilter.Files.name": string;
  "rowFilter.Files.storageProviderId": string;
  "rowFilter.Files.storageProviderPath": string;
  "rowFilter.Files.type": string;
  "rowFilter.Files.size": string;
  "rowFilter.Files.description": string;
}

export interface operations {}

export interface external {}
