#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -e .json -e .ts -e .tsx -e .md | sed 's| |\\ |g')
ez2readts --files $FILES
npm run format -- $(git diff --cached --name-only --diff-filter=ACMR | grep -e .json -e .ts -e .tsx -e .md | sed 's| |\\ |g')
git add -A
